doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        schema_filter: "~^(?!(_timescaledb_catalog|_timescaledb_config|_timescaledb_internal|domotic_device_metric|system_log)).*$~"

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
        types:
            device_id: Marvin\Shared\Infrastructure\Persistence\Doctrine\DBAL\Types\DeviceIdType
            protocol_id: Marvin\Shared\Infrastructure\Persistence\Doctrine\DBAL\Types\ProtocolIdType
            user_id: Marvin\Shared\Infrastructure\Persistence\Doctrine\DBAL\Types\UserIdType
            uniq_id: Marvin\Shared\Infrastructure\Persistence\Doctrine\DBAL\Types\UniqIdType
            zone_id: Marvin\Shared\Infrastructure\Persistence\Doctrine\DBAL\Types\ZoneIdType
            email: Marvin\Shared\Infrastructure\Persistence\Doctrine\DBAL\Types\EmailType
            login_attempt_id: Marvin\Security\Infrastructure\Persistence\Doctrine\DBAL\Types\LoginAttemptIdType
            request_reset_password_id: Marvin\Security\Infrastructure\Persistence\Doctrine\DBAL\Types\RequestResetPasswordIdType
            container_id: Marvin\System\Infrastructure\Persistence\Doctrine\DBAL\Types\ContainerIdType
            worker_id: Marvin\System\Infrastructure\Persistence\Doctrine\DBAL\Types\WorkerIdType
            action_request_id: Marvin\System\Infrastructure\Persistence\Doctrine\DBAL\Types\ActionRequestIdType
    orm:
        auto_generate_proxy_classes: true
        enable_native_lazy_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: false
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            Marvin\Shared:
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/ORM/Shared'
                prefix: 'Marvin\Shared\Domain'
                is_bundle: false
            Marvin\Security:
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/ORM/Security'
                prefix: 'Marvin\Security\Domain'
                is_bundle: false
            Marvin\System:
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/ORM/System'
                prefix: 'Marvin\System\Domain'
                is_bundle: false
            Marvin\Location:
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/ORM/Location'
                prefix: 'Marvin\Location\Domain'
                is_bundle: false
        controller_resolver:
            auto_mapping: false
when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
