doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        schema_filter: "~^(?!(_timescaledb_catalog|_timescaledb_config|_timescaledb_internal|domotic_device_metric|system_log)).*$~"

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
        types:
            email: Marvin\Shared\Infrastructure\Persistence\Doctrine\DBAL\Types\EmailType
            createdAt: Marvin\Shared\Infrastructure\Persistence\Doctrine\DBAL\Types\CreatedAtType
            updatedAt: Marvin\Shared\Infrastructure\Persistence\Doctrine\DBAL\Types\UpdatedAtType
            login_attempt_id: Marvin\Security\Infrastructure\Persistence\Doctrine\DBAL\Types\LoginAttemptIdType
            user_id: Marvin\Security\Infrastructure\Persistence\Doctrine\DBAL\Types\UserIdType
            request_reset_password_id: Marvin\Security\Infrastructure\Persistence\Doctrine\DBAL\Types\RequestResetPasswordIdType
            docker_id: Marvin\System\Infrastructure\Persistence\Doctrine\DBAL\Types\DockerIdType
            docker_command_id: Marvin\System\Infrastructure\Persistence\Doctrine\DBAL\Types\DockerCommandIdType
            plugin_id: Marvin\System\Infrastructure\Persistence\Doctrine\DBAL\Types\PluginIdType
            zone_id: Marvin\Domotic\Infrastructure\Persistence\Doctrine\DBAL\Types\ZoneIdType
            protocol_id: Marvin\Domotic\Infrastructure\Persistence\Doctrine\DBAL\Types\ProtocolIdType
            device_id: Marvin\Domotic\Infrastructure\Persistence\Doctrine\DBAL\Types\DeviceIdType
            group_id: Marvin\Domotic\Infrastructure\Persistence\Doctrine\DBAL\Types\GroupIdType
            capability_id: Marvin\Domotic\Infrastructure\Persistence\Doctrine\DBAL\Types\CapabilityIdType
            capability_action_id: Marvin\Domotic\Infrastructure\Persistence\Doctrine\DBAL\Types\CapabilityActionIdType
            capability_state_id: Marvin\Domotic\Infrastructure\Persistence\Doctrine\DBAL\Types\CapabilityStateIdType
            capability_composition_id: Marvin\Domotic\Infrastructure\Persistence\Doctrine\DBAL\Types\CapabilityCompositionIdType
    orm:
        auto_generate_proxy_classes: true
        enable_native_lazy_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: false
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            Marvin\Shared:
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/ORM/Shared'
                prefix: 'Marvin\Shared\Domain'
                is_bundle: false
            Marvin\Security:
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/ORM/Security'
                prefix: 'Marvin\Security\Domain'
                is_bundle: false
            Marvin\System:
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/ORM/System'
                prefix: 'Marvin\System\Domain'
                is_bundle: false
            Marvin\Domotic:
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/ORM/Domotic'
                prefix: 'Marvin\Domotic\Domain'
                is_bundle: false
        controller_resolver:
            auto_mapping: false
when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
