doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
        types:
            email: Marvin\Shared\Infrastructure\Persistence\Doctrine\DBAL\Types\EmailType
            createdAt: Marvin\Shared\Infrastructure\Persistence\Doctrine\DBAL\Types\CreatedAtType
            updatedAt: Marvin\Shared\Infrastructure\Persistence\Doctrine\DBAL\Types\UpdatedAtType
            login_attempt_id: Marvin\Security\Infrastructure\Persistence\Doctrine\DBAL\Types\LoginAttemptIdType
            user_id: Marvin\Security\Infrastructure\Persistence\Doctrine\DBAL\Types\UserIdType
            user_status_id: Marvin\Security\Infrastructure\Persistence\Doctrine\DBAL\Types\UserStatusIdType
            user_type_id: Marvin\Security\Infrastructure\Persistence\Doctrine\DBAL\Types\UserTypeIdType
    orm:
        auto_generate_proxy_classes: true
        enable_native_lazy_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: false
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            #Domotic:
            #    type: attribute
            #    is_bundle: false
            #    dir: '%kernel.project_dir%/src/Domotic/Domain'
            #    prefix: 'Marvin\Domotic\Domain'
            Marvin\Shared:
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/ORM/Shared'
                prefix: 'Marvin\Shared\Domain'
                is_bundle: false
            Marvin\Security:
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/ORM/Security'
                prefix: 'Marvin\Security\Domain'
                is_bundle: false
            #System:
            #    type: attribute
            #    is_bundle: false
            #    dir: '%kernel.project_dir%/src/System/Domain'
            #    prefix: 'Marvin\System\Domain'
        controller_resolver:
            auto_mapping: false
when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
