twig:
    file_name_pattern: '*.twig'
    paths:
        'src/Security/Presentation/Web/Templates': ~
        'src/Shared/Presentation/Web/Templates': ~

when@test:
    twig:
        strict_variables: true
