twig:
    file_name_pattern: '*.twig'
    paths:
        'src/Security/Presentation/Mail': 'security_mail'
        'src/Shared/Presentation/Mail': 'shared_mail'

when@test:
    twig:
        strict_variables: true
